/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shunter' at '1/23/17 9:51 AM' with Gradle 2.13
 *
 * @author shunter, @date 1/23/17 9:51 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
